/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AdminDashboardController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author KOMPUTER
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NavPanel = new javax.swing.JPanel();
        managemovieBtn = new javax.swing.JButton();
        viewbookingsBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        ManageMoviePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MovieTable = new javax.swing.JTable();
        createBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        ViewBookingPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewBookingsTable = new javax.swing.JTable();
        SearchTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ViewInvoice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("admin");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NavPanel.setBackground(new java.awt.Color(255, 255, 255));
        NavPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        managemovieBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/managemoviesBtnHover.png"))); // NOI18N
        managemovieBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managemovieBtnActionPerformed(evt);
            }
        });
        NavPanel.add(managemovieBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 180, 36));

        viewbookingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/viewBookingsBtn.png"))); // NOI18N
        viewbookingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbookingsBtnActionPerformed(evt);
            }
        });
        NavPanel.add(viewbookingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 144, 180, 34));

        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/logoutBtn.png"))); // NOI18N
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        NavPanel.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 196, 180, 30));

        getContentPane().add(NavPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 500));

        ManageMoviePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MovieTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "movie_title", "genre", "rating", "date", "time", "showtime", "content_rating", "screen", "ticket_pricing"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MovieTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MovieTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(MovieTable);

        ManageMoviePanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 660, 380));

        createBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/createBtn.png"))); // NOI18N
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        ManageMoviePanel.add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 70, 30));

        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/editBtn.png"))); // NOI18N
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        ManageMoviePanel.add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 70, 30));

        getContentPane().add(ManageMoviePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 720, 500));

        ViewBookingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewBookingsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id_book", "id_customer", "id_movie", "movie_title", "genre", "seat", "purchased_date", "total_amount", "created_at"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        viewBookingsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewBookingsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(viewBookingsTable);

        ViewBookingPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 600, 370));
        ViewBookingPanel.add(SearchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 180, -1));

        jLabel1.setText("Cari");
        ViewBookingPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 30, 20));

        ViewInvoice.setText("View Invoice");
        ViewInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewInvoiceActionPerformed(evt);
            }
        });
        ViewBookingPanel.add(ViewInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, -1, -1));

        getContentPane().add(ViewBookingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 720, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void managemovieBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managemovieBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managemovieBtnActionPerformed

    private void MovieTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovieTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MovieTableMouseClicked

    private void viewbookingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbookingsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewbookingsBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBtnActionPerformed

    private void viewBookingsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBookingsTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viewBookingsTableMouseClicked

    private void ViewInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewInvoiceActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminDashboard view = new AdminDashboard();
                new AdminDashboardController(view); // Initialize controller
                view.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ManageMoviePanel;
    private javax.swing.JTable MovieTable;
    private javax.swing.JPanel NavPanel;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JPanel ViewBookingPanel;
    private javax.swing.JButton ViewInvoice;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton managemovieBtn;
    private javax.swing.JTable viewBookingsTable;
    private javax.swing.JButton viewbookingsBtn;
    // End of variables declaration//GEN-END:variables

    public JPanel getManageMoviePanel() {
        return ManageMoviePanel;
    }

    public void setManageMoviePanel(JPanel ManageMoviePanel) {
        this.ManageMoviePanel = ManageMoviePanel;
    }

    public JTable getMovieTable() {
        return MovieTable;
    }

    public void setMovieTable(JTable MovieTable) {
        this.MovieTable = MovieTable;
    }

    public JPanel getNavPanel() {
        return NavPanel;
    }

    public void setNavPanel(JPanel NavPanel) {
        this.NavPanel = NavPanel;
    }

    public JTextField getSearchTextField() {
        return SearchTextField;
    }

    public void setSearchTextField(JTextField SearchTextField) {
        this.SearchTextField = SearchTextField;
    }

    public JPanel getViewBookingPanel() {
        return ViewBookingPanel;
    }

    public void setViewBookingPanel(JPanel ViewBookingPanel) {
        this.ViewBookingPanel = ViewBookingPanel;
    }

    public JButton getViewInvoice() {
        return ViewInvoice;
    }

    public void setViewInvoice(JButton ViewInvoice) {
        this.ViewInvoice = ViewInvoice;
    }

    public JButton getCreateBtn() {
        return createBtn;
    }

    public void setCreateBtn(JButton createBtn) {
        this.createBtn = createBtn;
    }

    public JButton getEditBtn() {
        return editBtn;
    }

    public void setEditBtn(JButton editBtn) {
        this.editBtn = editBtn;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JButton getLogoutBtn() {
        return logoutBtn;
    }

    public void setLogoutBtn(JButton logoutBtn) {
        this.logoutBtn = logoutBtn;
    }

    public JButton getManagemovieBtn() {
        return managemovieBtn;
    }

    public void setManagemovieBtn(JButton managemovieBtn) {
        this.managemovieBtn = managemovieBtn;
    }

    public JTable getViewBookingsTable() {
        return viewBookingsTable;
    }

    public void setViewBookingsTable(JTable viewBookingsTable) {
        this.viewBookingsTable = viewBookingsTable;
    }

    public JButton getViewbookingsBtn() {
        return viewbookingsBtn;
    }

    public void setViewbookingsBtn(JButton viewbookingsBtn) {
        this.viewbookingsBtn = viewbookingsBtn;
    }

}
